### PR TITLE
Adds info regarding S3 and Netlify to README.md

### PR DESCRIPTION
**Pull request by davidsneal**

### CODE REVIEW

**Comment by jasonvarga** [comment]
Not that I don't believe you, but can you point out where Netlify is doing this?

**Comment by davidsneal** [comment]
https://imgur.com/a/FMUupW4

Hope these screenshots suffice. So in the log I saw something wasn't quite right with the region, then when I tried to set any of the regular .env vars I got the warning shown.

**Comment by jasonvarga** [comment]
Is it just AWS_REGION that conflicts? Or is it all of the AWS related vars in .env?

If it's just the region, the one in our .env file is actually AWS_DEFAULT_REGION.

**Comment by davidsneal** [comment]
Sorry you're right, I did that from memory, the default region is fine. So it looks like there's actually only two that are affected https://imgur.com/a/cV76S2w

**Comment by jasonvarga** [comment]
How weird. Feels like maybe this means you can connect to AWS from elsewhere in Netlify or something. Can't find anything about that though.

Anyway, I'll merge. Thanks!

**Comment by davidsneal** [comment]
Nice, thanks. There's nothing documented that I can see, but I reckon it could be to do with the custom tier, where you can deploy to your own AWS account.

**Pull request merged**
