### PR TITLE
Glide Improvements

### LINKED ISSUE #55: Slow when using Glide with S3
This is not really unexpected since its gotta read the images from S3.

But, I thought if I keep the glide cached images around, it would be fast. This isn't true because we create a separate Glide cache inside the ssg output directory.

https://github.com/statamic/ssg/blob/aa9c1436924c9269eda42a27930c46398c301dbd/src/Generator.php#L101-L103

Maybe there can be a "before" step where it copies the cached files over. I tried doing it manually, and it clears out the directory. Might be something that Flysystem does? Not sure.

### LINKED ISSUE #56: Slow when using Reponsive Images addon
Related to #55

The [responsive images](https://github.com/spatie/statamic-responsive-images) seems to generate more variants than I would have expected. Need to work out _why_, and really understand the rationale behind which variants should be generated and make the ssg use those somehow.

The addon has to do with browser size. Since there's no browser, we might need to fake something.

(@riasvdv - You don't have to spend any time on this, but if any of this sounds familiar to you, a tip in the right direction would be helpful)

### LINKED ISSUE #103: Images not being generated
This is a recent issue (like, has only been a problem in the last couple of weeks).

Running `php please ssg:generate` isn't generating the image files for newly added content. Anything older than a couple of weeks ago is working fine, but anything added in the last couple of weeks fails to create.

For clarity, the local "live" version of the site works fine, the static version is missing the new images.

No idea where to start debugging this - any pointers/things I can try?

### PR DESCRIPTION
**Pull request by jasonvarga**
This PR does two things:

- Allows the Glide override to be disabled.
  - Fixes #55
  - Fixes #56
- Clears the Glide cache store when using the default override.
  - Fixes #103

### Problem

By default, the SSG would reconfigure Glide to use the "cached" option and generate stuff into a directory within the static folder. This was necessary if you had the default Glide setup in Statamic which used the dynamic routes. The SSG would therefore need to generate the images at template-render-time.

However, each time you run the SSG, the whole static directory would get cleared, which includes your Glide generated images. Meaning the next time you run it, it would need to generate all the Glide images again.

### Solution

Since there were [improvements to Glide within the core](https://github.com/statamic/cms/pull/5725), there are now better options than the override the SSG does. You can now tell the SSG to *not* override Glide and instead opt to leverage the improved core features. (The default is still to override it to maintain backwards compatibility.)

The main way to speed things up is to have the Glide generated images stick around between SSG generations.

For example you can have your images be generated to some directory (using the [custom path glide setting](https://statamic.dev/image-manipulation#custom-path-static)), then copy that directory into the right place in your static folder.

```php
// config/statamic/assets.php
'image_manipulation' => [
  'cache' => true,
  'cache_path' => public_path('img'),
]
```
```php
// config/statamic/ssg.php
'glide' => [
    'override' => false,
],
```
```php
SSG::after(function () {
    $from = public_path('img');
    $to = config('statamic.ssg.destination').'/img';
    app('files')->copyDirectory($from, $to);
});
```

Or, if you [put your Glide images on S3](https://statamic.dev/image-manipulation#custom-disk-cdn), you can just set `'override' => false`, and rely on the S3 URLs. No copying necessary.

### Caveat

You need to adjust your config as mentioned above in order to get a speed increase. It's not going to happen just by upgrading.

### CODE REVIEW

**Comment by jasonvarga** [comment]
You can put it inside your `AppServiceProvider`'s `boot` method.

**Comment by mbootsman** [comment]
I've added it like so:
```
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Statamic\Statamic;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }

    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        // Statamic::script('app', 'cp');
        // Statamic::style('app', 'cp');
        
        SSG::after(function () {
            $from = public_path('img');
            $to = config('statamic.ssg.destination').'/img';
            app('files')->copyDirectory($from, $to);
        });
    }
}
```
When I then run `php please ssg:generate`, I get this error:   `Class "App\Providers\SSG" not found`
SSG is installed with `composer require statamic/ssg`

**Comment by jasonvarga** [comment]
Make sure to import the class at the top of the file with the other `use` statements.

```diff
use Illuminate\Support\ServiceProvider;
use Statamic\Statamic;
+use Statamic\StaticSite\SSG;
```

**Comment by mbootsman** [comment]
@jasonvarga Doh! Thanks, that did the trick :+1:

**Pull request merged**
